"""progress2_yolo_confidence_persistence

Revision ID: 52a0d9bf8914
Revises: b8a2c5f1e734
Create Date: 2026-05-28 21:53:04.110304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a0d9bf8914'
down_revision = 'b8a2c5f1e734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hazard_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detection_confidence', sa.Numeric(precision=5, scale=4), nullable=True))
        batch_op.add_column(sa.Column('detection_low_confidence', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hazard_reports', schema=None) as batch_op:
        batch_op.drop_column('detection_low_confidence')
        batch_op.drop_column('detection_confidence')

    # ### end Alembic commands ###
