"""progress2_archive_lifecycle

Revision ID: 964630ff1d5a
Revises: 52a0d9bf8914
Create Date: 2026-05-30 09:03:47.210661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964630ff1d5a'
down_revision = '52a0d9bf8914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hazard_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'admins', ['archived_by'], ['admin_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hazard_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('archived_by')
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
